version: "2"
services:
  flask-api:
    build: .
    links:
      - mysqldb
    ports:
      - "8001:8000"
  mysqldb:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: titanicdb
      MYSQL_ROOT_HOST: '%'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  
     