apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-api
  name: flask-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: flask-api
    spec:
      containers:
      - image: dockeropticca/sherweb_api:v1
        name: flask-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
