project: "sherweb-poject"
name_cluster: "cluster-sherweb-api-1"
zone: "us-central1-a"
machine_type: "n1-standard-1"
disk_type: "pd-standard"
disk_size: "10"
num_nodes: "2"
region: "us-central1"
auth_kind: serviceaccount
service_account_file: sherweb-poject-sa.json
network: "projects/{{project}}/global/networks/default"
subnetwork: "projects/{{project}}/regions/us-central1/subnetworks/default"
